# Generated by Django 4.1.1 on 2022-09-30 09:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 9, 42, 25, 620728, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='option',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 9, 42, 25, 620886, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='question',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 9, 42, 25, 621243, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='question',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 9, 42, 25, 621253, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='quiz',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 9, 42, 25, 621653, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='quiz',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 9, 42, 25, 621658, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='quizquestionanswer',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 9, 42, 25, 621993, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='quizquestionanswer',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 9, 42, 25, 621998, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='quizquestionanswer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
